### ISSUE TITLE
May vertx-stack/stack-npm/src/main/npm/client/package.json include sockjs as dependency?

### ISSUE THREAD

**Issue by xcracr** [vert-x3/vertx-stack#37]
Hello, may package.json list sockjs-client as a dependency?  Then when installed via `npm install vertx3-eventbus-client` it would install sockjs-client under its local node_modules directory, which is helpful when developing for client javascript using [browserify](http://browserify.org/) or [webpack](https://webpack.github.io/).

**Comment by cescoffier** [comment]
@pmlopes : what do you think ?

**Comment by pmlopes** [comment]
I think that is a good idea. We might need to review the examples though...

**Comment by cescoffier** [comment]
Should it be considered as a breaking change ?

**Comment by pmlopes** [comment]
i don't think so, i've not tested it but i think that if we add the dependency to the package.json and the already existing projects would also add the dependency npm should be smart and just use one of the dependencies right? In the worst case there will be 2 downloads of the same dependency on the client side which is not a big deal since at runtime only 1 will be used.

**Comment by cescoffier** [comment]
Ok, I will apply it.
