### ISSUE TITLE
Release new version, plz

### ISSUE THREAD

**Issue by joh-klein** [vert-x3/vertx-stack#66]
The [vertx-eventbus.js](https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/client/vertx-eventbus.js) is a little newer. When are you planning to release a newer version?
Also, the sockjs-client is available in a newer version as well.

**Comment by cescoffier** [comment]
Hi @joh-klein we should have a release next week (it's an estimation, not a date written somewhere).

**Comment by joh-klein** [comment]
Since you have the "old" (vertx 2.~) version in the other repo as well, what are the chances of pushing both to npm? I am trying to get rid of bower.

**Comment by cescoffier** [comment]
The vert.x 3 version is on NPM already.

**Comment by joh-klein** [comment]
I know,  but I am wondering about the vert.x 2 eventbus js file.

**Comment by cescoffier** [comment]
@pmlopes WDYT ?

**Comment by joh-klein** [comment]
It would be great to get it from the official source. I know it is deprecated, but I will have to support some vert.x 2 backends for at least the next year.

**Comment by pmlopes** [comment]
Maybe you're not aware but the old version is already available on cdnjs is that an option? https://cdnjs.cloudflare.com/ajax/libs/vertx/2.0.0/vertxbus.min.js

**Comment by joh-klein** [comment]
But I can only [use tarball URLs inside a package.json](https://docs.npmjs.com/files/package.json#urls-as-dependencies) …

**Comment by pmlopes** [comment]
@joh-klein by using the CDN you don't need to use tar balls. Also if you're using tools such as `gulp` you can use a plugin like: `https://www.npmjs.com/package/gulp-cdnizer` that at release time will fetches the resource from the CDN to your local distribution directory.

**Comment by joh-klein** [comment]
@pmlopes I am not sure how to respond to this. Using npm is not the same as linking to a CDN. I put fixed versions of my modules in my package.json. I need the guarantee, that nothing has changed. Also, I need the possibility of letting my apps run offline. There are countless reasons for using npm (and of course for using a CDN). Sure, I can always take your version and put it on my private npm registry, but I like using the official repo. I would appreciate it, if you would reconsider.

**Comment by pmlopes** [comment]
I understand the reasons behind disconnected apps vs online, that is why I put the gulp plugin here as an option to solve this gap. https://www.npmjs.com/package/gulp-cdnizer

We're currently working on version 3.x and this is our main focus so we would like to stay away from making new 2.x releases. Having this said, we know that the version on npm 3.1.0 is very close to the script used in the 2.x series, you could try that one first, since it includes the `vertxbus.js` and now the current one.

They are not 100% the same though, for example the login function is not there since that was a 2.x specific feature.
